### ISSUE TITLE
Implement iOS Support?

### ISSUE THREAD

**Issue by Johnny5sword** [mdrokz/ani_mobile#11]
Hello!

It would be great if the .ipa is available so iOS users can sideload this app using [Altstore](https://altstore.io/)(iOS 12.2+) or [Sideloadly](https://sideloadly.io/)(iOS 7+).

Unfortunately, I can't build it because I don't have a Mac or know others who have one.

If it is released, I also hope it will have compatibility with iOS 9.3 because it's the last OS version available for my device.
Thank you!

Edit: It looks like [Flutter SDK](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) versions [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip)(Stable), April 2022 and [2.13.0-0.4.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_2.13.0-0.4.pre-beta.zip)(Beta), May 2022 were the last releases to support arm7v 32-bit iOS such as my version of iOS 9 based from this [document](https://docs.google.com/document/d/1Xz8B2w42ZGmrSdvQHo6LVLhiSZBIxnHxZxoZ-8oyRUc/mobilebasic).

**Comment by mdrokz** [comment]
> Hello!
> 
> It would be great if the .ipa is available so iOS users can sideload this app using [Altstore](https://altstore.io/)(iOS 12.2+) or [Sideloadly](https://sideloadly.io/)(iOS 7+).
> 
> Unfortunately, I can't build it because I don't have a Mac or know others who have one.
> 
> If it is released, I also hope it will have compatibility with iOS 9.3 because it's the last OS version available for my device. Thank you!
> 
> Edit: It looks like [Flutter SDK](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) versions [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip)(Stable), April 2022 and [2.13.0-0.4.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_2.13.0-0.4.pre-beta.zip)(Beta), May 2022 were the last releases to support arm7v 32-bit iOS such as my version of iOS 9 based from this [document](https://docs.google.com/document/d/1Xz8B2w42ZGmrSdvQHo6LVLhiSZBIxnHxZxoZ-8oyRUc/mobilebasic).

Hello sorry for late reply, i would want to support IOS but i myself dont have an Mac device so its really difficult for me to support IOS. i hope you understand :)

**Comment by mdrokz** [comment]
> > Hello!
> > It would be great if the .ipa is available so iOS users can sideload this app using [Altstore](https://altstore.io/)(iOS 12.2+) or [Sideloadly](https://sideloadly.io/)(iOS 7+).
> > Unfortunately, I can't build it because I don't have a Mac or know others who have one.
> > If it is released, I also hope it will have compatibility with iOS 9.3 because it's the last OS version available for my device. Thank you!
> > Edit: It looks like [Flutter SDK](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) versions [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip)(Stable), April 2022 and [2.13.0-0.4.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_2.13.0-0.4.pre-beta.zip)(Beta), May 2022 were the last releases to support arm7v 32-bit iOS such as my version of iOS 9 based from this [document](https://docs.google.com/document/d/1Xz8B2w42ZGmrSdvQHo6LVLhiSZBIxnHxZxoZ-8oyRUc/mobilebasic).
> 
> Hello sorry for late reply, i would want to support IOS but i myself dont have an Mac device so its really difficult for me to support IOS. i hope you understand :)

I have found this https://medium.com/team-rockstars-it/the-easiest-way-to-build-a-flutter-ios-app-using-github-actions-plus-a-key-takeaway-for-developers-48cf2ad7c72a i will look into this if its possible to use GH actions to build it

**Comment by mdrokz** [comment]
> Hello!
> 
> It would be great if the .ipa is available so iOS users can sideload this app using [Altstore](https://altstore.io/)(iOS 12.2+) or [Sideloadly](https://sideloadly.io/)(iOS 7+).
> 
> Unfortunately, I can't build it because I don't have a Mac or know others who have one.
> 
> If it is released, I also hope it will have compatibility with iOS 9.3 because it's the last OS version available for my device. Thank you!
> 
> Edit: It looks like [Flutter SDK](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) versions [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip)(Stable), April 2022 and [2.13.0-0.4.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_2.13.0-0.4.pre-beta.zip)(Beta), May 2022 were the last releases to support arm7v 32-bit iOS such as my version of iOS 9 based from this [document](https://docs.google.com/document/d/1Xz8B2w42ZGmrSdvQHo6LVLhiSZBIxnHxZxoZ-8oyRUc/mobilebasic).

Hi can you check the ipa in this release ? https://github.com/mdrokz/ani_mobile/releases/tag/0.1.9

**Comment by Johnny5sword** [comment]
Hello!
Sorry for the late reply.
Unfortunately, installation fails for me because of DeviceOSVersionTooLow (Have 9.3.5; need 11.0).
Anyways, thanks for providing an .ipa so technically iOS support is implemented
